### ISSUE TITLE
HTTP 401 error when attemtping to build 

### ISSUE THREAD

**Issue by TheD0ubleT** [corda/confidential-identities#28]
**Summary**
When trying to build the library (master branch), the build process returns an error when attempting to access the `quasar-core` library.

Going to the software.r3.com website, the JFrog platform, to manually search for the repo refuses to let me see any library with an error `You are not authorized to view this page`. It wants me to login, however there is no way to register or create an account on the JFrog platform.

**Error logs**
Here is the error logs when trying to run `./gradlew.bat clean install`

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'confidential-identities'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve net.corda.plugins:cordapp:5.0.15.
     Required by:
         project :
      > Could not resolve net.corda.plugins:cordapp:5.0.15.
         > Could not get resource 'https://software.r3.com/artifactory/corda-releases/net/corda/plugins/cordapp/5.0.15/cordapp-5.0.15.pom'.
            > Could not GET 'https://software.r3.com/artifactory/corda-releases/net/corda/plugins/cordapp/5.0.15/cordapp-5.0.15.pom'. Received status code 401 from server:
   > Could not resolve net.corda.plugins:cordformation:5.0.15.
     Required by:
         project :
      > Could not resolve net.corda.plugins:cordformation:5.0.15.
         > Could not get resource 'https://software.r3.com/artifactory/corda-releases/net/corda/plugins/cordformation/5.0.15/cordformation-5.0.15.pom'.
            > Could not GET 'https://software.r3.com/artifactory/corda-releases/net/corda/plugins/cordformation/5.0.15/cordformation-5.0.15.pom'. Received status code 401 from server:
   > Could not resolve net.corda.plugins:quasar-utils:5.0.15.
     Required by:
         project :
      > Could not resolve net.corda.plugins:quasar-utils:5.0.15.
         > Could not get resource 'https://software.r3.com/artifactory/corda-releases/net/corda/plugins/quasar-utils/5.0.15/quasar-utils-5.0.15.pom'.
            > Could not GET 'https://software.r3.com/artifactory/corda-releases/net/corda/plugins/quasar-utils/5.0.15/quasar-utils-5.0.15.pom'. Received status code 401 from server:

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
```

**Expected**
Successful compilation of the library

**Additional information**

A similar error (different url for another library but identical error) occures when attemting to compile the Accounts libreary or a cordapp that uses this library

This has started happening today and it worked and compiled fine last Friday.

**Comment by ronanbrowne** [comment]
@TheD0ubleT, Thanks for flagging this.

We recently changed our use of Artifactory to be internal only with an alternative mirror provided, the default branch `release/1.1` was updated with the solution, but I see you are working off the `master`, which does not have this fix.

A PR has been merged to master to rectify this if you could update your project and retry

**Comment by stephanelatil** [comment]
Thank you for the help, everything seems to work now 👍
